### ISSUE TITLE
Remove Docusaurus Default Documentation from Blog Section

### ISSUE THREAD

**Issue by thecloudcode** [pizofreude/TheCADMan#7]
**Description**:  
In the blog section of the project, there are still references and content from Docusaurus default documentation (e.g., sample blog posts and code snippets referencing Docusaurus features). These placeholders need to be replaced with relevant content specific to the project.

**Steps to Reproduce**:
1. Navigate to the blog section of the site.
2. Observe the presence of sample posts like "MDX Blog Post" with Docusaurus references.

**Expected Behavior**:  
The blog section should contain posts and information relevant to the project's content rather than default Docusaurus documentation.

**Proposed Solution**:  
- Remove or replace the default Docusaurus blog posts and tips.
- Add relevant posts and information that aligns with the project's focus and objectives.

**Screenshots**:  
(Attach the screenshot showing the issue for reference.)

**Additional Context**:  
This change will help in improving the professional look of the blog section and ensure it aligns with the project's identity.

**Comment by Gurvinder-Singh02** [comment]
i would love to resolve this issue can you assign me this

**Comment by pizofreude** [comment]
Alright, it's yours @Gurvinder-Singh02

**Comment by thecloudcode** [comment]
Hi @pizofreude, I am the one who found this issue, kindly assign it to me.

**Comment by pizofreude** [comment]
> Hi @pizofreude, I am the one who found this issue, kindly assign it to me.

Hi @thecloudcode, this issue is already closed. Feel free to suggest any further improvement. Writing blog will also be accepted. Thanks for your help. Much appreciated.
